name: 'Deploy action'
description: 'Deploy custom action'
inputs:
  name:
    description: 'name used'
    required: false
    default: 'Hello'
outputs:
  action-result:
    description: 'result from action'
    value: ${{ steps.save-var.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Virtual deployment
      shell: bash
      run: echo "Start deployment..."
    - name: Next one
      if: success()
      shell: bash
      run: echo "Done.. yes ${{ inputs.name }}"
    - name: Save var
      id: save-var
      shell: bash
      run: echo "result=Hello Salouma" >> $GITHUB_OUTPUT