name: build project
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  build:
    name: build micro-service
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Spring Gradle Build Action
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: build project
        run: ./gradlew clean build
