name: Build project
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - release
    path-ignore:
      - 'README.md'
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
    path-ignore:
      - 'README.md'
jobs:
  build:
    name: Build micro-service
    runs-on: ubuntu-latest
    outputs:
      build-file: ${{ steps.publish.outputs.build-filename }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Spring Gradle Build Action
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build project
        run: ./gradlew clean build
      - name: Publish build filename
        id: publish
        # Display the filename and save it
        run: find build/libs/*plain* -type f -execdir echo 'build-filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/libs
  deploy:
    name: Deploy to INT environment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: Display job artifacts
        run: ls
      - name: Job output from build
        run: echo ${{ needs.build.outputs.build-file }}
      - name: Virtual deployment
        run: echo "Start deployment..."
