name: using Reusable workflow
on:
  push:
    branches:
      -feature
jobs:
  build:
    name: Build micro-service
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Spring Gradle Build Action
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build project
        run: ./gradlew clean build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/libs
  deploy:
    needs: build
    name: Deployment
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: build-files
    secrets:
      user-name: ${{ secrets.username }}
  print:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: let's print
        run: echo ${{ needs.deploy.outputs.result }}

