name: Reusable build
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Get value from parent
        required: false
        default: build-files
        type: string
jobs:
  deploy:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        run: action/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Virtual deployment
        run: echo "Start deployment ..."
